export const POINTS_OF_INTEREST = [
  "Bar",
  "Cafe",
  "Convenience Store",
  "Dentist",
  "Dog Park",
  "Elementary School",
  "Fast-food Restaurant",
  "Gym",
  "Hospital",
  "Kindergarten",
  "Parcel Locker",
  "Pediatrician",
  "Pharmacy",
  "Playground",
  "Post Office",
  "Pub",
  "Public Transport Stop",
  "Restaurant",
  "Supermarket",
]
